import "@uploadthing/react/styles.css";
import "../globals.css";
import { Montserrat } from "next/font/google";
import Nav from "@/components/Nav";
import Provider from "@/components/Provider";
import Footer from "@/components/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <html lang="hu">
      <body className={montserrat.className}>
        <Provider>
          <div className="max-w-7xl m-auto p-4">
            <header>
              <Nav />
            </header>
            <main>
              {children}
            </main>
          </div>
          <footer>
            <Footer />
          </footer>
        </Provider>
      </body>
    </html>
  );
}
